version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-xwiki
    restart: always
    networks:
      - xwiki-net
    environment:
      POSTGRES_USER: xwiki
      POSTGRES_PASSWORD: xwiki
      POSTGRES_DB: xwiki
    volumes:
      - postgres_data:/var/lib/postgresql/data

  xwiki:
    image: xwiki:14.10.17-postgres-tomcat  # Vulnerable Version
    container_name: xwiki
    restart: always
    depends_on:
      - postgres
    networks:
      - xwiki-net
    ports:
      - "8080:8080"
    environment:
      DB_USER: xwiki
      DB_PASSWORD: xwiki
      DB_DATABASE: xwiki
      DB_HOST: postgres

networks:
  xwiki-net:

volumes:
  postgres_data:
